name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v1

      - name: Zip rozkladzik dir
        run: |
          cd /home/runner/work/Home-Assistant-custom-components-Rozkladzik/Home-Assistant-custom-components-Rozkladzik/custom_components/rozkladzik
          zip rozkladzik.zip -r ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/Home-Assistant-custom-components-Rozkladzik/Home-Assistant-custom-components-Rozkladzik/custom_components/rozkladzik/rozkladzik.zip
          asset_name: rozkladzik.zip
          tag: ${{ github.ref }}
          overwrite: true